### ISSUE TITLE
Adding weapons after selecting attachments breaks comparison selectrons

### ISSUE THREAD

**Issue by Miffyli** [Miffyli/sym#38]
If you select attachments to a weapon first and then select second weapon, the attachments in the first weapon do not apply correctly.

To replicate:
1) Go to comparison page
2) Select first weapon and some attachments to it
3) Select second weapon to be same as the first one
4) Page now shows the first one has selected attachments, but both weapons have same stats (where second one does not have any attachments selected)

**Comment by robenter** [comment]
Seems to only affect the 1stselection box.  It behaves normally and until a weapon is selected in the 2nd box.  At that moment, all the customization buttons of the first box read as "not checked" even though the boxes are orange.  They are radio buttons behind the scenes.  I suspect that they are being reset when the 1st box gets cloned to create the 3rd box.  One thing to try would be to have an invisible box that never gets used but is only used for cloning.

**Comment by Miffyli** [comment]
After giving it a look that could cause more headache. Is there a way to do that cleanly with the current code that it does not get too arcane-y? I tried looking at the root cause of this problem but so far nothing.

**Comment by robenter** [comment]
yeah, im pretty sure I can fix it.  i just wrote all that stuff cause I didnt have the time to implement the fix  but didnt' want to forget anything.  I can try after work today.

**Comment by robenter** [comment]
Fixed it by cloning the last dropdown box instead of the first dropdown box.  the last one will always not have any buttons yet so cloning it doesnt seem to affect anything
