### ISSUE TITLE
New weapons not being sorted by class/type filters on BFV weapon chart page.

### ISSUE THREAD

**Issue by IncarnateNA** [Miffyli/sym#52]
This effects the following weapons:
- Model 37
- M2 Carbine
- BAR M1918A2
- M3 Grease Gun
- Nambu Type 2A
- Type 11 MG
- Type 97 MG

**Comment by Miffyli** [comment]
@robenter Did I forget to update some list for these?

**Comment by robenter** [comment]
Yes, I can work on it tomorrow along with some other things.

**Comment by robenter** [comment]
Fixed.  bfv_chart.js needs to be updated when there are new guns.
