### ISSUE TITLE
Warzone sym upgrade

### ISSUE THREAD

**Issue by bloodsinc** [Miffyli/sym#60]
Hello , firstly thanks to the best sym website , wanna say about some improvements on a warzone sym web , when u do comparison in bitween 5 weapons , when u choose the head ( or torso or another limb ) of the body , mb u can do that if u pick head , all of 5 weapons choose the head option , because when u choose it now , just your current comparison weapon chooses , so u need to click all of 5 tabs and choose the head in TTK options

**Comment by IncarnateNA** [comment]
This is a very recent bug and will be addressed very shortly with an update

**Comment by Miffyli** [comment]
Closing as resolved in advance to avoid many open issues :).
